name: RedLightGreenLight
version: 1.0.0
main: com.iTimess.redlightgreenlight.RedLightGreenLight
api-version: 1.20
commands:
  rlg:
    description: Main command for Red Light Green Light
    usage: /<command>
    aliases: [redlight, greenlight]